- project_name: hello-world
  organization_unit: demos
  owner_name: owner-1
  reviewers:
    code_review:
      - reviewer-1
  skip_reviews: []
  job_name: init-project
  campaign_type: software/python/simple/create
  runtime_variables:
    filename: main.py
  input_contexts:
    workspace/original_requirements: Create a program to print "Hello World".