name: Windows Single Round Run

on:
  workflow_dispatch:

jobs:
  run_windows_single_round_run:
    runs-on: windows-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Environment Preparations
      uses: ./.github/actions/windows-preparation

    - name: Run Application
      run: python main.py --work-only -n 1